### ISSUE TITLE
[Bug/Typo]:  DORA metrics scripts for lead generation time, time import is missing in script

### ISSUE THREAD

**Issue by Hardik-Murdia** [port-labs/port-docs#1069]
### Description

I found an issue with the DORA metric lead time changes script where import time is not present because of which if someone directly copy paste it the script will fail (link) [https://github.com/port-labs/port-docs/blob/6ead978d51b2873e3dfc2c869101dddfeefdc8b9/docs/build-your-software-catalog/custom-integration/api/ci-cd/github-workflow/guides/dora-metrics.md#L4]
Error observed :
![image](https://github.com/port-labs/port-docs/assets/58582570/5844ed0d-5cbe-4a25-be59-9c91116ce0a8)

The import has to be added in the script as shown in script 
import time
![image](https://github.com/port-labs/port-docs/assets/58582570/68a95916-2eec-4471-bec5-0d470f080afd)

LOC where failure is observed:
![image](https://github.com/port-labs/port-docs/assets/58582570/2a8c5b74-4ea6-4ad4-9d75-54995c6ded2f)

this might be missed in testing as this is part of a github related issue

**Comment by Hardik-Murdia** [comment]
I have tested it in git actions and during the DORA integration I found the issue 
![image](https://github.com/port-labs/port-docs/assets/58582570/9bdcf6bb-c834-4afb-b667-e40a33dd6530)

**Comment by Hardik-Murdia** [comment]
> Thanks @Hardik-Murdia

most welcome

**Comment by hadar-co** [comment]
@Hardik-Murdia resolved, if you encounter the issue again, please re-open:) Thanks for reporting!
