### ISSUE TITLE
[Feature]: Additional documentation/examples around what markdown-based dashboard widget capabilities are available

### ISSUE THREAD

**Issue by reinrl** [port-labs/port-docs#1715]
### 🚀 Feature Proposal

In the current document for a [Markdown dashboard widget](https://docs.getport.io/customize-pages-dashboards-and-plugins/dashboards/#markdown), the main body is highlighted as being a spot to enter markdown. After viewing the current Port demo portal (and follow on conversation with support), it appears that there is also ability to use certain subsets of HTML within the same widget. Can the documentation be expanded to cover this additional functionality?

### Motivation and example

Being able to understand the full capabilities of this widget type (both now, and if they are expanded/enhanced in the future) would be much appreciated!

**Comment by hadar-co** [comment]
@reinrl thanks for reporting this, we'll make sure to add info to the docs 💯
